---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.python_pip
      # python_pip_update: false
    - role: robertdebock.buildtools
    - role: robertdebock.openssl
      openssl_items:
        - name: apache-httpd
          common_name: "{{ ansible_fqdn }}"
    - role: robertdebock.httpd
