---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Run php --version
      ansible.builtin.command:
        cmd: php --version
      register: php_version

    - name: Show php_version
      ansible.builtin.debug:
        msg: "{{ php_version.stdout }}"

    - name: Place php_info
      ansible.builtin.copy:
        content: "<?php phpinfo(); ?>"
        dest: php_info.php

    - name: Run php php_info.php
      ansible.builtin.command:
        cmd: php php_info.php
